/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

import database.ConnectionManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.User;

/**
 *
 * @author noreen
 */
public class LoanProductConfigPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanProductConfigPanel
     */
    private User currentUser;
        
    public LoanProductConfigPanel(User user) {
        this.currentUser = user;
        initComponents();
        productTypeComboBox.addActionListener(evt -> {
            String selectedProduct = (String) productTypeComboBox.getSelectedItem();
            loadLoanProductConfig(selectedProduct);
        });
        loadLoanProductConfig((String) productTypeComboBox.getSelectedItem());
    }
    
        private void loadLoanProductConfig(String productName) {
        try (Connection conn = ConnectionManager.getConnection()) {
            String query = "SELECT * FROM loan_products WHERE name = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, productName);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                interestRateField.setText(String.valueOf(rs.getDouble("interest_rate")));
                minAmountField.setText(String.valueOf(rs.getDouble("min_amount")));
                maxAmountField.setText(String.valueOf(rs.getDouble("max_amount")));
                minMonthsField.setText(String.valueOf(rs.getInt("min_term")));
                maxMonthsField.setText(String.valueOf(rs.getInt("max_term")));
                allowVIPCheckBox.setSelected(rs.getBoolean("allow_vip"));
                allowRegularCheckBox.setSelected(rs.getBoolean("allow_regular"));
                allowNewCheckBox.setSelected(rs.getBoolean("allow_new"));
                cleanHistoryCheckBox.setSelected(rs.getBoolean("require_clean_history"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading product config: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        productTypeComboBox = new javax.swing.JComboBox<>();
        interestRateField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        minAmountField = new javax.swing.JTextField();
        maxAmountField = new javax.swing.JTextField();
        minMonthsField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        maxMonthsField = new javax.swing.JTextField();
        allowVIPCheckBox = new javax.swing.JCheckBox();
        allowRegularCheckBox = new javax.swing.JCheckBox();
        allowNewCheckBox = new javax.swing.JCheckBox();
        cleanHistoryCheckBox = new javax.swing.JCheckBox();
        saveButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 246, 250));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Product type:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Loan Terms:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Interest Rate:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Min Amount:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Max Amount:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Term (months):");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setText("Eligibility:");

        productTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Education Loan", "Business Loan", "Emergency Loan" }));

        interestRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestRateFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("%");

        minAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minAmountFieldActionPerformed(evt);
            }
        });

        maxAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxAmountFieldActionPerformed(evt);
            }
        });

        minMonthsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minMonthsFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("-");

        maxMonthsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxMonthsFieldActionPerformed(evt);
            }
        });

        allowVIPCheckBox.setForeground(new java.awt.Color(47, 54, 64));
        allowVIPCheckBox.setText("Allow VIP Clients");
        allowVIPCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowVIPCheckBoxActionPerformed(evt);
            }
        });

        allowRegularCheckBox.setForeground(new java.awt.Color(47, 54, 64));
        allowRegularCheckBox.setText("Allow Regular Clients");
        allowRegularCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowRegularCheckBoxActionPerformed(evt);
            }
        });

        allowNewCheckBox.setForeground(new java.awt.Color(47, 54, 64));
        allowNewCheckBox.setText("Allow New Clients");
        allowNewCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allowNewCheckBoxActionPerformed(evt);
            }
        });

        cleanHistoryCheckBox.setForeground(new java.awt.Color(47, 54, 64));
        cleanHistoryCheckBox.setText("Require Clean Loan History");
        cleanHistoryCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanHistoryCheckBoxActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(0, 51, 102));
        saveButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save Changes");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(interestRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(minAmountField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(maxAmountField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(minMonthsField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(maxMonthsField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allowRegularCheckBox)
                                    .addComponent(allowVIPCheckBox)
                                    .addComponent(allowNewCheckBox)
                                    .addComponent(cleanHistoryCheckBox)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(144, 144, 144))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(productTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(interestRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(minAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(allowVIPCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allowRegularCheckBox)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(maxAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(minMonthsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(maxMonthsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(allowNewCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanHistoryCheckBox)))
                .addGap(38, 38, 38)
                .addComponent(saveButton)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void interestRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interestRateFieldActionPerformed

    private void minAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minAmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minAmountFieldActionPerformed

    private void maxAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxAmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxAmountFieldActionPerformed

    private void minMonthsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minMonthsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minMonthsFieldActionPerformed

    private void maxMonthsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxMonthsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxMonthsFieldActionPerformed

    private void allowVIPCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowVIPCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allowVIPCheckBoxActionPerformed
    
    private void allowRegularCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowRegularCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allowRegularCheckBoxActionPerformed

    private void allowNewCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allowNewCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allowNewCheckBoxActionPerformed

    private void cleanHistoryCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanHistoryCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanHistoryCheckBoxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (
            interestRateField.getText().trim().isEmpty() ||
            minAmountField.getText().trim().isEmpty() ||
            maxAmountField.getText().trim().isEmpty() ||
            minMonthsField.getText().trim().isEmpty() ||
            maxMonthsField.getText().trim().isEmpty()
        ) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        try {
            String productName = (String) productTypeComboBox.getSelectedItem();
            double rate = Double.parseDouble(interestRateField.getText().trim());
            double minAmount = Double.parseDouble(minAmountField.getText().trim());
            double maxAmount = Double.parseDouble(maxAmountField.getText().trim());
            int minTerm = Integer.parseInt(minMonthsField.getText().trim());
            int maxTerm = Integer.parseInt(maxMonthsField.getText().trim());

            boolean vipBox = allowVIPCheckBox.isSelected();
            boolean regularBox = allowRegularCheckBox.isSelected();
            boolean newBox = allowNewCheckBox.isSelected();
            boolean cleanHistory = cleanHistoryCheckBox.isSelected();

            Connection conn = ConnectionManager.getConnection();
            String sql = """
                UPDATE loan_products SET 
                    interest_rate = ?, min_amount = ?, max_amount = ?, 
                    min_term = ?, max_term = ?, 
                    allow_vip = ?, allow_regular = ?, allow_new = ?, 
                    require_clean_history = ?
                WHERE name = ?
            """;

            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setDouble(1, rate);
            pstmt.setDouble(2, minAmount);
            pstmt.setDouble(3, maxAmount);
            pstmt.setInt(4, minTerm);
            pstmt.setInt(5, maxTerm);
            pstmt.setBoolean(6, vipBox);
            pstmt.setBoolean(7, regularBox);
            pstmt.setBoolean(8, newBox);
            pstmt.setBoolean(9, cleanHistory);
            pstmt.setString(10, productName);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Product configuration updated!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allowNewCheckBox;
    private javax.swing.JCheckBox allowRegularCheckBox;
    private javax.swing.JCheckBox allowVIPCheckBox;
    private javax.swing.JCheckBox cleanHistoryCheckBox;
    private javax.swing.JTextField interestRateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maxAmountField;
    private javax.swing.JTextField maxMonthsField;
    private javax.swing.JTextField minAmountField;
    private javax.swing.JTextField minMonthsField;
    private javax.swing.JComboBox<String> productTypeComboBox;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
