/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package admin;

import database.DatabaseHelper;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import models.User;
import java.sql.SQLException;

/**
 *
 * @author noreen
 */
public class PriorityRulesPanel extends javax.swing.JPanel {

   
    
    private User currentUser;
    
    public PriorityRulesPanel(User user) {
        this.currentUser = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        creditHistoryField = new javax.swing.JTextField();
        incomeLevelField = new javax.swing.JTextField();
        loanPurposeField = new javax.swing.JTextField();
        existingDebtField = new javax.swing.JTextField();
        clientTypeField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        approvalThresholdField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 246, 250));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Scoring Weights:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Credit History:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Income Level:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Loan Purpose:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Existing Debt:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Client Type:");

        creditHistoryField.setText("30");
        creditHistoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditHistoryFieldActionPerformed(evt);
            }
        });

        incomeLevelField.setText("25");
        incomeLevelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeLevelFieldActionPerformed(evt);
            }
        });

        loanPurposeField.setText("15");
        loanPurposeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanPurposeFieldActionPerformed(evt);
            }
        });

        existingDebtField.setText("10");
        existingDebtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingDebtFieldActionPerformed(evt);
            }
        });

        clientTypeField.setText("20");
        clientTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientTypeFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("%");

        jLabel8.setText("%");

        jLabel9.setText("%");

        jLabel10.setText("%");

        jLabel11.setText("%");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("Auto-Approval Threshold:");

        approvalThresholdField.setText("85");
        approvalThresholdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvalThresholdFieldActionPerformed(evt);
            }
        });

        jLabel13.setText("%");

        saveButton.setBackground(new java.awt.Color(0, 51, 102));
        saveButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save Rules");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(0, 51, 102));
        resetButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset to Default");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel12)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(creditHistoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(incomeLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(loanPurposeField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(existingDebtField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(clientTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(approvalThresholdField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(creditHistoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(incomeLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(loanPurposeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(existingDebtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(clientTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(approvalThresholdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(resetButton))
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creditHistoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditHistoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditHistoryFieldActionPerformed

    private void incomeLevelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeLevelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incomeLevelFieldActionPerformed

    private void loanPurposeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanPurposeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanPurposeFieldActionPerformed

    private void existingDebtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingDebtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existingDebtFieldActionPerformed

    private void clientTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientTypeFieldActionPerformed

    private void approvalThresholdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvalThresholdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_approvalThresholdFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    if (
        creditHistoryField.getText().trim().isEmpty() ||
        incomeLevelField.getText().trim().isEmpty() ||
        loanPurposeField.getText().trim().isEmpty() ||
        existingDebtField.getText().trim().isEmpty() ||
        clientTypeField.getText().trim().isEmpty() ||
        approvalThresholdField.getText().trim().isEmpty()
    ) {
        JOptionPane.showMessageDialog(this, "Please fill in all the fields before saving.");
        return;
    }

    try {
        // Parse all values safely inside the try block
        int CreditHistory = Integer.parseInt(creditHistoryField.getText().trim());
        int IncomeLevel = Integer.parseInt(incomeLevelField.getText().trim());
        int LoanPurpose = Integer.parseInt(loanPurposeField.getText().trim());
        int ExistingDebt = Integer.parseInt(existingDebtField.getText().trim());
        int ClientType = Integer.parseInt(clientTypeField.getText().trim());
        int ApprovalThreshold = Integer.parseInt(approvalThresholdField.getText().trim());

        int total = CreditHistory + IncomeLevel + LoanPurpose + ExistingDebt + ClientType;
        if (total != 100) {
            JOptionPane.showMessageDialog(this, "Scoring must sum to 100%");
            return;
        }

        DatabaseHelper.executeUpdate(
            "UPDATE rules_config SET " +
            "credit_weight = ?, " +
            "income_weight = ?, " +
            "purpose_weight = ?, " +
            "debt_weight = ?, " +
            "client_weight = ?, " +
            "auto_approve_threshold = ? " +
            "WHERE rule_id = ?",
            CreditHistory, IncomeLevel, LoanPurpose, ExistingDebt, ClientType, ApprovalThreshold, 1
        );

        JOptionPane.showMessageDialog(this, "Rules updated");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numbers only.");
    }catch (HeadlessException | SQLException e) {
 
                
}
    }//GEN-LAST:event_saveButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
     try {
        creditHistoryField.setText("30");
        incomeLevelField.setText("25");
        loanPurposeField.setText("15");
        existingDebtField.setText("10");
        clientTypeField.setText ("20");
        approvalThresholdField.setText("85");

        DatabaseHelper.executeUpdate(
            "UPDATE rules_config SET " +
            "credit_weight = ?, " +
            "income_weight = ?, " +
            "purpose_weight = ?, " +
            "debt_weight = ?, " +
            "client_weight = ?, " +
            "auto_approve_threshold = ? " +
            "WHERE rule_id = ?",
            30, 25, 15, 10, 20, 85, 1
        );
                
        JOptionPane.showMessageDialog(this, "Fields have been reset.");
    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Reset failed: " + e.getMessage());
    }    
    // Show a confirmation dialog (optional)
    JOptionPane.showMessageDialog(this, "Reset success.");

    }//GEN-LAST:event_resetButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField approvalThresholdField;
    private javax.swing.JTextField clientTypeField;
    private javax.swing.JTextField creditHistoryField;
    private javax.swing.JTextField existingDebtField;
    private javax.swing.JTextField incomeLevelField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField loanPurposeField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
