/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package applicant;

import models.User;
import java.sql.ResultSet;
import database.DatabaseHelper;
import javax.swing.JOptionPane;
/**
 *
 * @author noreen
 */
public class ApplicationStatusPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApplicationStatusPanel
     */
    private User currentUser;
    private int maxCredit = 0, maxIncome = 0, maxPurpose = 0, maxDebt = 0;
    private int autoApprove = 0, autoReject = 0;
    private int clientWeight = 0;
    
    public ApplicationStatusPanel(User user) {
        this.currentUser = user;
        initComponents();
        loadApplicationStatus();
    }
    
    public void refreshStatus() {
    loadApplicationStatus();
}
        
    private void loadApplicationStatus() {
    try {
        fetchMaxScores(); 

        String query = """
            SELECT la.application_id, la.status, la.submission_date, la.priority_level,
                   es.credit_score, es.income_score, es.purpose_score, es.debt_score, es.client_score,
                   u.client_type
            FROM loan_applications la
            JOIN users u ON la.applicant_id = u.user_id
            LEFT JOIN evaluation_scores es ON la.application_id = es.application_id
            WHERE la.applicant_id = ?
            ORDER BY la.application_id DESC
            LIMIT 1
        """;

        ResultSet rs = DatabaseHelper.executeQuery(query, currentUser.getUserId());

        if (rs.next()) {
            applicationIDLabel.setText(String.valueOf(rs.getInt("application_id")));
            statusLabel.setText(rs.getString("status"));
            submittedLabel.setText(rs.getString("submission_date"));
            priorityLabel.setText(rs.getString("priority_level"));

            int creditScore = rs.getInt("credit_score");
            int incomeScore = rs.getInt("income_score");
            int purposeScore = rs.getInt("purpose_score");
            int debtScore = rs.getInt("debt_score");
            int clientScore = rs.getInt("client_score");

            creditHistoryLabel.setText(formatScore(creditScore, maxCredit));
            incomeLevelLabel.setText(formatScore(incomeScore, maxIncome));
            loanPurposeLabel.setText(formatScore(purposeScore, maxPurpose));
            existingDebtLabel.setText(formatScore(debtScore, maxDebt));
            clientTypeLabel.setText(formatScore(clientScore, clientWeight));
        } else {
            statusUpdateLabel.setText("No application found.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to load application status.");
    }
    }

    private void fetchMaxScores() {
        try {
            ResultSet rs = DatabaseHelper.executeQuery("SELECT * FROM rules_config LIMIT 1");
            if (rs.next()) {
                maxCredit = rs.getInt("credit_weight");
                maxIncome = rs.getInt("income_weight");
                maxPurpose = rs.getInt("purpose_weight");
                maxDebt = rs.getInt("debt_weight");
                
            autoApprove = rs.getInt("auto_approve_threshold");
            autoReject = rs.getInt("auto_reject_threshold");
            clientWeight = rs.getInt("client_weight"); 
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private String formatScore(Object scoreObj, int maxScore) {
    if (scoreObj == null) return "(N/A)";
    int score = (int) scoreObj;

    // Show + only if positive
    String sign = (score >= 0) ? "+" : "";
    return String.format("(%s%d/%d)", sign, score, maxScore);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        applicationIDLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        submittedLabel = new javax.swing.JLabel();
        priorityLabel = new javax.swing.JLabel();
        creditHistoryLabel = new javax.swing.JLabel();
        incomeLevelLabel = new javax.swing.JLabel();
        loanPurposeLabel = new javax.swing.JLabel();
        existingDebtLabel = new javax.swing.JLabel();
        clientTypeLabel = new javax.swing.JLabel();
        statusUpdateLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 246, 250));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Application ID:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Status:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Submitted:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Priority:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setText("Score Breakdown: ");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Credit History: ");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Income Level:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Loan Purpose:");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("Existing Debt:");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("Client Type:");

        statusUpdateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(statusUpdateLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addComponent(clientTypeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(applicationIDLabel)
                            .addComponent(statusLabel)
                            .addComponent(submittedLabel)
                            .addComponent(priorityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(5, 5, 5))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel9))))
                                    .addGap(2, 2, 2)))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incomeLevelLabel)
                            .addComponent(loanPurposeLabel)
                            .addComponent(existingDebtLabel)
                            .addComponent(creditHistoryLabel))))
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(applicationIDLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(statusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(submittedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(priorityLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(creditHistoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(incomeLevelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(loanPurposeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(existingDebtLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(clientTypeLabel))
                .addGap(116, 116, 116)
                .addComponent(statusUpdateLabel)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicationIDLabel;
    private javax.swing.JLabel clientTypeLabel;
    private javax.swing.JLabel creditHistoryLabel;
    private javax.swing.JLabel existingDebtLabel;
    private javax.swing.JLabel incomeLevelLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel loanPurposeLabel;
    private javax.swing.JLabel priorityLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusUpdateLabel;
    private javax.swing.JLabel submittedLabel;
    // End of variables declaration//GEN-END:variables
}
