/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package applicant;

import models.User;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author noreen
 */
public class LoanHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanHistoryPanel
     */
    private User currentUser;
    
    public LoanHistoryPanel(User user) {
        this.currentUser = user;
        initComponents();
        loadLoanHistory();
    }

    public void refreshTable() {
    loadLoanHistory();
}
    
    private void loadLoanHistory() {
    try {
        DefaultTableModel model = (DefaultTableModel) loanHistoryTable.getModel();
        model.setRowCount(0); // clear existing rows

        String query = """
            SELECT la.application_id, la.submission_date, la.amount, la.status, lh.repaid
            FROM loan_applications la
            LEFT JOIN loan_history lh ON la.application_id = lh.application_id
            WHERE la.applicant_id = ?
            ORDER BY la.application_id DESC
        """;

        ResultSet rs = database.DatabaseHelper.executeQuery(query, currentUser.getUserId());
        while (rs.next()) {
            int appId = rs.getInt("application_id");
            String date = rs.getString("submission_date");
            double amount = rs.getDouble("amount");
            String status = rs.getString("status");
            boolean repaid = rs.getBoolean("repaid");

            model.addRow(new Object[] {
                appId,
                date,
                String.format("₱%,.2f", amount),
                status,
                repaid ? "Yes" : "No"
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to load loan history.");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        loanHistoryTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 246, 250));

        loanHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "App ID", "Date", "Amount", "Status", "Paid?"
            }
        ));
        jScrollPane1.setViewportView(loanHistoryTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable loanHistoryTable;
    // End of variables declaration//GEN-END:variables
}
