/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package applicant;

import models.User;
import javax.swing.*;
import java.sql.ResultSet;
import database.DatabaseHelper;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author noreen
 */
public class LoanFormPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanFormPanel
     */
private User currentUser;
private double minAmount = 0;
private double maxAmount = 0;
private int minTerm = 1;
private int maxTerm = 12;


public LoanFormPanel(User user) {
    this.currentUser = user;
    initComponents();
    loanTypeComboBoxActionPerformed(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loanTypeLabel = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        termLabel = new javax.swing.JLabel();
        purposeLabel = new javax.swing.JLabel();
        incomeLabel = new javax.swing.JLabel();
        loanTypeComboBox = new javax.swing.JComboBox<>();
        amountField = new javax.swing.JTextField();
        termSpinner = new javax.swing.JSpinner();
        purposeComboBox = new javax.swing.JComboBox<>();
        incomeField = new javax.swing.JTextField();
        requirementsLabel = new javax.swing.JLabel();
        instructionLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 246, 250));

        loanTypeLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        loanTypeLabel.setForeground(new java.awt.Color(47, 54, 64));
        loanTypeLabel.setText("Loan Type:");

        amountLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        amountLabel.setForeground(new java.awt.Color(47, 54, 64));
        amountLabel.setText("Amount:");

        termLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        termLabel.setForeground(new java.awt.Color(47, 54, 64));
        termLabel.setText("Term(Months):");

        purposeLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        purposeLabel.setForeground(new java.awt.Color(47, 54, 64));
        purposeLabel.setText("Purpose:");

        incomeLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        incomeLabel.setForeground(new java.awt.Color(47, 54, 64));
        incomeLabel.setText("Monthly Income:");

        loanTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Education Loan", "Business Loan", "Emergency Loan" }));
        loanTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanTypeComboBoxActionPerformed(evt);
            }
        });

        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });

        purposeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tuition / School Fees", "Books / Supplies", "Business Expansion", "Capital for Startup", "Emergency Medical", "Utility Bills", "Personal / Family Use" }));
        purposeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purposeComboBoxActionPerformed(evt);
            }
        });

        incomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeFieldActionPerformed(evt);
            }
        });

        requirementsLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        requirementsLabel.setForeground(new java.awt.Color(47, 54, 64));
        requirementsLabel.setText("Requirements:");

        instructionLabel.setForeground(new java.awt.Color(47, 54, 64));
        instructionLabel.setText("<html>Please submit emailed copies of your ID, payslip, and co-maker form within 3 days to complete your application.<br><br>Send to:<br>loan.docs@gmail.com</html>");

        submitButton.setBackground(new java.awt.Color(0, 51, 102));
        submitButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("• Valid ID");

        jLabel2.setText("• Latest Payslip");

        jLabel3.setText("• Co-maker Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(incomeLabel)
                            .addComponent(purposeLabel)
                            .addComponent(termLabel)
                            .addComponent(amountLabel)
                            .addComponent(loanTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loanTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(amountField)
                            .addComponent(termSpinner)
                            .addComponent(purposeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(incomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(requirementsLabel)
                            .addComponent(instructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))))
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(requirementsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(instructionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loanTypeLabel)
                            .addComponent(loanTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountLabel)
                            .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(termLabel)
                            .addComponent(termSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(purposeLabel)
                            .addComponent(purposeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(incomeLabel)
                            .addComponent(incomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(submitButton)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            String loanType = loanTypeComboBox.getSelectedItem().toString();
            String amountStr = amountField.getText().trim();
            String incomeStr = incomeField.getText().trim();
            int term = (int) termSpinner.getValue();
            String purpose = purposeComboBox.getSelectedItem().toString();

            if (amountStr.isEmpty() || incomeStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields.");
                return;
            }

            double amount = Double.parseDouble(amountStr);
            double income = Double.parseDouble(incomeStr);

            if (amount < minAmount || amount > maxAmount) {
                JOptionPane.showMessageDialog(this,
                    "Loan amount must be between ₱" + String.format("%,.2f", minAmount)
                    + " and ₱" + String.format("%,.2f", maxAmount),
                    "Invalid Amount", JOptionPane.WARNING_MESSAGE);
                return;
            }

            ResultSet rs = DatabaseHelper.executeQuery("SELECT product_id FROM loan_products WHERE name = ?", loanType);
            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Selected loan type not found in database.");
                return;
            }

            int productId = rs.getInt("product_id");

            DatabaseHelper.executeUpdate(
                "INSERT INTO loan_applications (applicant_id, product_id, amount, term_months, purpose, status, submission_date) VALUES (?, ?, ?, ?, ?, 'In Review', NOW())",
                currentUser.getUserId(), productId, amount, term, purpose
            );

            ResultSet appRs = DatabaseHelper.executeQuery("SELECT LAST_INSERT_ID() AS app_id");
            appRs.next();
            int appId = appRs.getInt("app_id");

            ResultSet ruleRs = DatabaseHelper.executeQuery("SELECT * FROM rules_config LIMIT 1");
            int creditWeight = 0, incomeWeight = 0, purposeWeight = 0, debtWeight = 0;
            int autoApprove = 0, autoReject = 0;
            if (ruleRs.next()) {
                creditWeight = ruleRs.getInt("credit_weight");
                incomeWeight = ruleRs.getInt("income_weight");
                purposeWeight = ruleRs.getInt("purpose_weight");
                debtWeight = ruleRs.getInt("debt_weight");
                autoApprove = ruleRs.getInt("auto_approve_threshold");
                autoReject = ruleRs.getInt("auto_reject_threshold");
            }

            int creditScore = creditWeight;
            int incomeScore = (income >= 30000) ? incomeWeight : Math.min(incomeWeight, (int)(income / 30000.0 * incomeWeight));
            int purposeScore = (purpose.contains("Business") || purpose.contains("Tuition")) ? purposeWeight : purposeWeight / 2;
            int debtScore = debtWeight;

            ResultSet userRs = DatabaseHelper.executeQuery("SELECT client_type FROM users WHERE user_id = ?", currentUser.getUserId());
            String clientType = "New"; // default
            if (userRs.next()) {
                clientType = userRs.getString("client_type");
            }

            // Get client_score_weight from rules_config
            int clientWeight = ruleRs.getInt("client_weight");
            int clientScore = switch (clientType.toLowerCase()) {
                case "vip" -> clientWeight;
                case "regular" -> clientWeight / 2;
                default -> 0; // New client
            };

            int totalScore = creditScore + incomeScore + purposeScore + debtScore + clientScore;
            
            String priority;
            if (totalScore >= autoApprove) {
                priority = "Platinum";
            } else if (totalScore >= 70) {
                priority = "Gold";
            } else if (totalScore >= autoReject) {
                priority = "Silver";
            } else {
                priority = "Red";
            }

            DatabaseHelper.executeUpdate(
                "INSERT INTO evaluation_scores (application_id, credit_score, income_score, purpose_score, debt_score, client_score, total_score) VALUES (?, ?, ?, ?, ?, ?, ?)",
                appId, creditScore, incomeScore, purposeScore, debtScore, clientScore, totalScore
            );

            String status = "In Review";
            if (priority.equals("Platinum")) {
                status = "Auto-Approved";
            } else if (priority.equals("Red")) {
                status = "Auto-Rejected";
            }

            DatabaseHelper.executeUpdate(
                "UPDATE loan_applications SET priority_level = ?, status = ? WHERE application_id = ?",
                priority, status, appId
            );

            JOptionPane.showMessageDialog(this, "Loan application submitted and scored successfully!");

            amountField.setText("");
            termSpinner.setValue(minTerm);
            incomeField.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Amount and income must be valid numbers. Avoid letters or commas.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred while submitting your application.");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void loanTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanTypeComboBoxActionPerformed
    try {
        String selectedLoan = loanTypeComboBox.getSelectedItem().toString();

        // Fetch loan product limits
        ResultSet rs = DatabaseHelper.executeQuery(
            "SELECT * FROM loan_products WHERE name = ?", selectedLoan
        );

        if (rs.next()) {
            minAmount = rs.getDouble("min_amount");
            maxAmount = rs.getDouble("max_amount");
            minTerm = rs.getInt("min_term");
            maxTerm = rs.getInt("max_term");

            // Apply limits to termSpinner
            SpinnerNumberModel spinnerModel = new SpinnerNumberModel(minTerm, minTerm, maxTerm, 1);
            termSpinner.setModel(spinnerModel);
        } else {
            JOptionPane.showMessageDialog(this, "Loan type not found in database.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading product limits.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_loanTypeComboBoxActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void purposeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purposeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purposeComboBoxActionPerformed

    private void incomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incomeFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField incomeField;
    private javax.swing.JLabel incomeLabel;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> loanTypeComboBox;
    private javax.swing.JLabel loanTypeLabel;
    private javax.swing.JComboBox<String> purposeComboBox;
    private javax.swing.JLabel purposeLabel;
    private javax.swing.JLabel requirementsLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel termLabel;
    private javax.swing.JSpinner termSpinner;
    // End of variables declaration//GEN-END:variables
}
