/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package officer;

import database.DatabaseHelper;
import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import models.LoanApplication;
import models.User;
/**
 *
 * @author noreen
 */
public class LoanQueuePanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanQueuePanel
     */
    private User currentUser;
    
    public LoanQueuePanel(User user) throws SQLException {
        this.currentUser = user;
        initComponents();
        ResultSet rs = DatabaseHelper.executeQuery(
        "SELECT * FROM dashboard " +
        "ORDER BY FIELD(priority_level, 'Platinum', 'Gold', 'Silver', 'Red')"
    );

    List<LoanApplication> applications = new ArrayList<>();
    while (rs.next()) {
        LoanApplication app = new LoanApplication();
        app.setApplicationId(rs.getLong("application_id"));
        app.setFullName(rs.getString("full_name"));
        app.setProduct(rs.getString("product"));
        app.setAmount(rs.getBigDecimal("amount"));
        app.setPurpose(rs.getString("purpose"));
        app.setStatus(rs.getString("status"));
        app.setPriorityLevel(rs.getString("priority_level"));
        applications.add(app);
    }
    populateTableWithColors(applications);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        QueueTable = new javax.swing.JTable();
        priorityFilterLabel = new javax.swing.JLabel();
        priorityFilterComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(245, 246, 250));

        QueueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "App ID", "Name", "Product", "Amount", "Purpose", "Status"
            }
        ));
        jScrollPane1.setViewportView(QueueTable);

        priorityFilterLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        priorityFilterLabel.setText("Priority Filter:");

        priorityFilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "In Review", "Gold", "Silver", "Red", "Platinum" }));
        priorityFilterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priorityFilterComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(priorityFilterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priorityFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priorityFilterLabel)
                    .addComponent(priorityFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void priorityFilterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priorityFilterComboBoxActionPerformed
        try {
            List<LoanApplication> applications = new ArrayList<>();
            Object selectedValue = priorityFilterComboBox.getSelectedItem();
            String selectedString = (String) priorityFilterComboBox.getSelectedItem();
            // get the selected string value from combobox then pass as parameter to where clause
            // String value = selected value .. TODO: research
            ResultSet rs;

            if ("All".equals(selectedString)) {
                rs = DatabaseHelper.executeQuery(
                    "SELECT * FROM dashboard " +
                    "ORDER BY FIELD(priority_level, 'Platinum', 'Gold', 'Silver', 'Red')"
                );

                while (rs.next()) {
                    LoanApplication app = new LoanApplication();
                    app.setApplicationId(rs.getLong("application_id"));
                    app.setFullName(rs.getString("full_name"));
                    app.setProduct(rs.getString("product"));
                    app.setAmount(rs.getBigDecimal("amount"));
                    app.setPurpose(rs.getString("purpose"));
                    app.setStatus(rs.getString("status"));
                    app.setPriorityLevel(rs.getString("priority_level"));
                    applications.add(app);
                }

                populateTableWithColors(applications);
            }

            else if ("In Review".equals(selectedString)) {
               rs = DatabaseHelper.executeQuery(
                   "SELECT * FROM dashboard WHERE status = 'In Review' " +
                   "ORDER BY FIELD(priority_level, 'Platinum', 'Gold', 'Silver', 'Red')"
               );
        
            while (rs.next()) {
                LoanApplication app = new LoanApplication();
                app.setApplicationId(rs.getLong("application_id"));
                app.setFullName(rs.getString("full_name"));
                app.setProduct(rs.getString("product"));
                app.setAmount(rs.getBigDecimal("amount"));
                app.setPurpose(rs.getString("purpose"));
                app.setStatus(rs.getString("status"));
                app.setPriorityLevel(rs.getString("priority_level"));
            
                applications.add(app);
            }
            
            populateTableWithColors(applications);
        }
            else{
                rs = DatabaseHelper.executeQuery(
                    "SELECT * FROM dashboard WHERE priority_level = ?",
                    selectedString
            );
            
            while (rs.next()) {
                LoanApplication app = new LoanApplication();
                app.setApplicationId(rs.getLong("application_id"));
                app.setFullName(rs.getString("full_name"));
                app.setProduct(rs.getString("product"));
                app.setAmount(rs.getBigDecimal("amount"));
                app.setPurpose(rs.getString("purpose"));
                app.setStatus(rs.getString("status"));
                app.setPriorityLevel(rs.getString("priority_level"));
            
                applications.add(app);
            }
            
            populateTableWithColors(applications);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoanQueuePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_priorityFilterComboBoxActionPerformed

    public final void populateTableWithColors(List<LoanApplication> applications) {
        ColoredTableModel model = new ColoredTableModel(applications);
        QueueTable.setModel(model);
        setupTableWithQueryColors();
    }
    
    public final List<LoanApplication> mapResultSetToList() throws SQLException {
        List<LoanApplication> applications = new ArrayList<>();
        
        ResultSet rs = DatabaseHelper.executeQuery(
                "SELECT * FROM dashboard;"
            );
        
        while (rs.next()) {
            LoanApplication app = new LoanApplication();
            app.setApplicationId(rs.getLong("application_id"));
            app.setFullName(rs.getString("full_name"));
            app.setProduct(rs.getString("product"));
            app.setAmount(rs.getBigDecimal("amount"));
            app.setPurpose(rs.getString("purpose"));
            app.setStatus(rs.getString("status"));
            app.setPriorityLevel(rs.getString("priority_level"));
            
            applications.add(app);
        }
        
        return applications;
    }
    
    public void setupTableWithQueryColors() {
        QueryBasedColorRenderer renderer = new QueryBasedColorRenderer();
        for (int i = 0; i < QueueTable.getColumnCount(); i++) {
            QueueTable.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }
    
    public void refreshTableData() {
        try {
            List<LoanApplication> data = this.mapResultSetToList();
            populateTableWithColors(data);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable QueueTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> priorityFilterComboBox;
    private javax.swing.JLabel priorityFilterLabel;
    // End of variables declaration//GEN-END:variables
}



class ColoredTableModel extends DefaultTableModel {
    private List<LoanApplication> applications;
    private final String[] columnNames = {
        "App ID", "Name", "Product", "Amount", "Purpose", "Status"
    };
    
    public ColoredTableModel(List<LoanApplication> applications) {
        this.applications = applications;
    }
    
    @Override
    public int getRowCount() {
        return applications != null ? applications.size() : 0;
    }
    
    @Override
    public int getColumnCount() {
        return columnNames.length;
    }
    
    @Override
    public String getColumnName(int column) {
        return columnNames[column];
    }
    
    @Override
    public Object getValueAt(int row, int column) {
        if (applications == null || row >= applications.size()) {
            return null;
        }
        
        LoanApplication app = applications.get(row);
        
        switch (column) {
            case 0: return app.getApplicationId();
            case 1: return app.getFullName();
            case 2: return app.getProduct();
            case 3: return app.getAmount();
            case 4: return app.getPurpose();
            case 5: return app.getStatus();
            default: return null;
        }
    }
    
    @Override
    public boolean isCellEditable(int row, int column) {
        return false;
    }
    
    // This method returns the priority level for coloring
    public String getRowColor(int row) {
        if (applications != null && row < applications.size()) {
            return applications.get(row).getPriorityLevel();
        }
        return null;
    }
    
    // Method to update data and refresh colors
    //public void updateData(List<LoanApplication> newApplications) {
    //    this.applications = newApplications;
    //    fireTableDataChanged();
    //}
}


class QueryBasedColorRenderer extends DefaultTableCellRenderer {
    
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column) {
        
        Component c = super.getTableCellRendererComponent(table, value, 
                isSelected, hasFocus, row, column);
        
        if (!isSelected) {
            if (table.getModel() instanceof ColoredTableModel) {
                ColoredTableModel model = (ColoredTableModel) table.getModel();
                String colorStr = model.getRowColor(row);
                
                if (colorStr != null && !colorStr.isEmpty()) {
                    Color rowColor = parseColor(colorStr);
                    if (rowColor != null) {
                        c.setBackground(rowColor);
                    } else {
                        c.setBackground(Color.WHITE);
                    }
                } else {
                    c.setBackground(Color.WHITE);
                }
            }
            c.setForeground(Color.BLACK);
        }
        
        return c;
    }
    
    private Color parseColor(String colorStr) {
        try {
            if (colorStr == null || colorStr.trim().isEmpty()) {
                return null;
            }
            
            colorStr = colorStr.trim().toUpperCase();
            
            switch (colorStr) {
                case "PLATINUM": return new Color(229, 228, 226);
                case "SILVER": return new Color(192, 192, 192);
                case "GOLD": return new Color(255, 215, 0);
                case "RED": return new Color(194, 24, 7);
                case "WHITE": return Color.WHITE;
                default: break;
            }
            
            // hex
            if (colorStr.startsWith("#")) {
                return Color.decode(colorStr);
            } else if (colorStr.matches("[0-9A-F]{6}")) {
                return Color.decode("#" + colorStr);
            }
            
            //rgb
            if (colorStr.contains(",")) {
                String[] rgb = colorStr.split(",");
                if (rgb.length == 3) {
                    int r = Integer.parseInt(rgb[0].trim());
                    int g = Integer.parseInt(rgb[1].trim());
                    int b = Integer.parseInt(rgb[2].trim());
                    return new Color(r, g, b);
                }
            }
            
        } catch (Exception e) {
            System.err.println("Error parsing color: " + colorStr + " - " + e.getMessage());
        }
        
        return null; 
    }
}

