/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package officer;

import database.DatabaseHelper;
import models.User;
import java.sql.*;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author noreen
 */
public class ReviewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReviewPanel
     */
    
    private User currentUser;
    private long currentApplicationId = -1;
    
    public ReviewPanel(User user) {
        this.currentUser = user;
        initComponents();
        loadApplicationDetails();
    }
    
        public void refreshStatus() {
            loadApplicationDetails();
        }

        private void loadApplicationDetails() {
    try {
        ResultSet rs = DatabaseHelper.executeQuery(
            "SELECT la.application_id, d.full_name, la.amount, la.term_months, es.total_score, la.priority_level " +
            "FROM loan_applications la " +
            "JOIN dashboard d ON la.application_id = d.application_id " +
            "JOIN evaluation_scores es ON la.application_id = es.application_id " +
            "WHERE la.status = 'In Review' AND es.is_evaluated = TRUE " +
            "ORDER BY FIELD(la.priority_level, 'Platinum', 'Gold', 'Silver', 'Red'), la.application_id " +
            "LIMIT 1"
        );

        if (rs.next()) {
            currentApplicationId = rs.getLong("application_id");

            nameLabel.setText(rs.getString("full_name"));
            double amount = rs.getDouble("amount");
            int term = rs.getInt("term_months");
            loanLabel.setText(String.format("₱%,.0f for %d months", amount, term));
            scoreLabel.setText(String.valueOf(rs.getInt("total_score")));
            flagLabel.setText("");  // clear any error
            approveButton.setEnabled(true);
            rejectButton.setEnabled(true);
        } else {
            // No more to review
            nameLabel.setText("");
            loanLabel.setText("");
            scoreLabel.setText("");
            flagLabel.setForeground(Color.RED);
            flagLabel.setText("No applications available for review.");
            approveButton.setEnabled(false);
            rejectButton.setEnabled(false);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading application: " + e.getMessage());
    }
    }
        
        private void updateApplicationStatus(String newStatus) {
        if (currentApplicationId == -1) return;

        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to label this application as " + newStatus.toLowerCase() + "?",
            "Confirm " + newStatus,
            JOptionPane.YES_NO_OPTION
        );

        if (choice != JOptionPane.YES_OPTION) return;

        try {
            int rowsAffected = DatabaseHelper.executeUpdate(
                "UPDATE loan_applications SET status = ? WHERE application_id = ?",
                newStatus, currentApplicationId
            );

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Application marked as: " + newStatus);
                loadApplicationDetails();  // move to the next application
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update status.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        approveButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        loanLabel = new javax.swing.JLabel();
        flagLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 246, 250));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Application Summary:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Score:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Loan:");

        approveButton.setBackground(new java.awt.Color(0, 51, 102));
        approveButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        approveButton.setForeground(new java.awt.Color(255, 255, 255));
        approveButton.setText("Approve");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        rejectButton.setBackground(new java.awt.Color(0, 51, 102));
        rejectButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        rejectButton.setForeground(new java.awt.Color(255, 255, 255));
        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scoreLabel)
                                    .addComponent(loanLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(approveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rejectButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(141, 141, 141))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(flagLabel)
                .addGap(315, 315, 315))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(scoreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(loanLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(approveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rejectButton)))
                .addGap(29, 29, 29)
                .addComponent(flagLabel)
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        updateApplicationStatus("Approved");
    }//GEN-LAST:event_approveButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        updateApplicationStatus("Rejected");
    }//GEN-LAST:event_rejectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveButton;
    private javax.swing.JLabel flagLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel loanLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton rejectButton;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
